export type StageName = "IF" | "ID" | "EX" | "MEM1" | "MEM2" | "WB";
export interface PipelineSlot { stage: StageName; valid: boolean; stalled: boolean; bubble: boolean; squashed: boolean; id: number; pc: number; raw: number; op: string; assembly: string; sourceLine: number; rs1: number; rs2: number; rd: number; immediate: number; operandA: number; operandB: number; aluResult: number; memoryAddress: number; memoryData: number; writeValue: number; regWrite: boolean; memRead: boolean; memWrite: boolean; predictedTaken: boolean; actualTaken: boolean; mispredicted: boolean; }
export interface CoreEvent { type: string; cycle: number; stage: string; instructionIds: number[]; reg: number; source: string; message: string; }
export interface Stats { cycles: number; fetched: number; retired: number; cpi: number; ipc: number; stallCycles: number; dataStallCycles: number; memoryStallCycles: number; controlPenalty: number; forwardingEvents: number; flushedInstructions: number; branches: number; correctPredictions: number; mispredictions: number; registerWrites: number; memoryWrites: number; }
export interface PredictorRow { index: number; valid: boolean; pc: number; state: number; prediction: boolean; recentTaken: boolean; }
export interface CacheLine { valid: boolean; dirty: boolean; tag: number; lru: number; preview: string; }
export interface CpuState { status: string; halted: boolean; faulted: boolean; pc: number; configuration: { forwarding: string; predictor: string; cacheEnabled: boolean }; registers: number[]; pipeline: PipelineSlot[]; statistics: Stats; events: CoreEvent[]; predictorTable: PredictorRow[]; cache: { reads: number; writes: number; hits: number; misses: number; dirtyWritebacks: number; sets: CacheLine[][] }; breakpoints: number[]; }
export interface TimelineFrame { cycle: number; stages: PipelineSlot[]; }
export interface AssemblyResult { ok: boolean; words: number[]; sourceLines: number[]; errors: { line: number; column: number; message: string }[]; }
export interface CoreSimulator { assemble(source: string): string; loadProgram(source: string): boolean; reset(): void; resetWithJson(config: string): void; stepCycle(): string; stepInstruction(): string; runCycles(count: number): string; runUntilCompletion(count?: number): string; runUntilBreakpoint(count?: number): string; getState(): string; getEvents(): string; getTimeline(): string; setBreakpoint(address: number, enabled: boolean): void; setRegister(index: number, value: number): void; readMemory(address: number, length: number): string; writeMemory(address: number, bytes: string): boolean; restorePreviousCycle(): boolean; delete(): void; }
