import { createHash } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceJs = resolve(root, process.argv[2] ?? "out/wasm/wasm-artifact/cpu_core.js");
const sourceWasm = resolve(root, process.argv[3] ?? "out/wasm/wasm-artifact/cpu_core.wasm");
const output = resolve(root, "frontend/src/generated");
const [sourceJavaScript, wasm] = await Promise.all([readFile(sourceJs), readFile(sourceWasm)]);

await WebAssembly.compile(wasm);
const build = createHash("sha256").update("vite-managed-v1").update(sourceJavaScript).update(wasm).digest("hex").slice(0, 16);
const jsName = `cpu_core.${build}.js`;
const wasmName = `cpu_core.${build}.wasm`;
const js = Buffer.from(sourceJavaScript.toString("utf8").replaceAll("'cpu_core.wasm'", `'${wasmName}'`));
const manifest = {
  build,
  js: jsName,
  wasm: wasmName,
  jsSha256: createHash("sha256").update(js).digest("hex"),
  wasmSha256: createHash("sha256").update(wasm).digest("hex"),
};
const moduleSource = `// Generated by scripts/publish-wasm.mjs; do not edit.\nimport createCpuLab from "./${jsName}";\nimport wasmUrl from "./${wasmName}?url";\nexport const WASM_BUILD = "${build}";\nexport { wasmUrl };\nexport default createCpuLab;\n`;

await mkdir(output, { recursive: true });
async function writeImmutable(name, contents) {
  const target = resolve(output, name);
  try {
    const existing = await readFile(target);
    if (Buffer.compare(existing, contents) !== 0) throw new Error(`Immutable artifact collision: ${name}`);
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
    await writeFile(target, contents, { flag: "wx" });
  }
}

await Promise.all([writeImmutable(jsName, js), writeImmutable(wasmName, wasm)]);

async function atomicWrite(name, contents) {
  const target = resolve(output, name);
  const temporary = `${target}.${process.pid}.tmp`;
  await writeFile(temporary, contents);
  await rename(temporary, target).catch(async () => writeFile(target, contents));
}

await Promise.all([
  atomicWrite("wasm-manifest.json", `${JSON.stringify(manifest, null, 2)}\n`),
  atomicWrite("wasm-artifact.ts", moduleSource),
]);

console.log(`Published WASM build ${build} from ${relative(root, sourceWasm)}`);
